[general]
import = ["one_dark.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"
[font.bold]
style = "Bold"
[font.italic]
style = "Italic"
[font.offset]
x = 0
y = 0

[window]
padding.x = 0
padding.y = 0
opacity = 1.0
decorations = "None"
dynamic_padding = false
