# General
[general]
import = ["~/.config/alacritty/one_dark.toml",]

# Environment
[env]
TERM = "xterm-256color"

# Keyboard
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"
[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

# Font
[font]
size = 11
[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"
[font.bold]
style = "Bold"
[font.italic]
style = "Italic"
[font.offset]
x = 1
y = 0

# Window
[scrolling]
history = 10000
[window]
title = "Alacritty"
[window.class]
general = "Alacritty"
instance = "Alacritty"
[window.padding]
x = 2
y = 2
