#!/usr/bin/env bash

# check if the interface is either tun0 or ppp0
if [[ "$IF" == "tun0" || "$IF" == "ppp0" ]]; then
  # check if tun0 or ppp0 exists in 'ip a'
  if ip a show $IF &>/dev/null; then
    echo "<span color='#129F12'>$IF</span>"
  else
    echo "<span color='#FA3721'>$IF</span>"
  fi
else
  # for other interfaces, check their status using 'ip a'
  interface_status=$(ip a show $IF 2>/dev/null | grep -oP '(?<=state )\w+')

  case "$interface_status" in
    up)
      echo "<span color='#12AF12'>$IF</span>"
      ;;
    down)
      echo "<span color='#FA3721'>$IF</span>"
      ;;
  esac
fi

